#!/bin/bash
# changelog.sh - Generate CHANGELOG.md from git history

# Get commits since last tag
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "HEAD")

# Get commits
COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:"%s" 2>/dev/null || git log --pretty=format:"%s")

# Create CHANGELOG.md
cat > CHANGELOG.md << 'EOF'
# Changelog

Generated by changelog.sh

## [Unreleased]

EOF

# Categorize commits
echo "$COMMITS" | while read line; do
    type=$(echo "$line" | grep -oE "^(feat|fix|docs|style|refactor|test|chore)" || echo "other")
    case "$type" in
        feat) echo "### Added" >> CHANGELOG.md ;;
        fix) echo "### Fixed" >> CHANGELOG.md ;;
        docs) echo "### Changed" >> CHANGELOG.md ;;
        style|refactor|test|chore) echo "### Changed" >> CHANGELOG.md ;;
        *) echo "### Other" >> CHANGELOG.md ;;
    esac
    echo "- $line" >> CHANGELOG.md
done

echo "CHANGELOG.md generated!"
